# sonar-project.properties
sonar.projectKey=NVT219045587_8.2C-nodejs-goof
sonar.organization=nvt219045587
sonar.host.url=https://sonarcloud.io
sonar.login=${SONAR_TOKEN}
sonar.sources=.
sonar.exclusions=node_modules/**,test/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.projectName=NodeJS Goof Vulnerable App
sonar.sourceEncoding=UTF-8